#!/bin/sh

system=$(uname -s)

case "$system" in
	Darwin)
		if [[ -x '/opt/homebrew/bin/pinentry-mac' ]]; then
			pinentry=/opt/homebrew/bin/pinentry-mac
		elif [[ -x '/usr/local/bin/pinentry-mac' ]]; then
			pinentry=/usr/local/bin/pinentry-mac
		elif [[ -x '/opt/homebrew/bin/pinentry' ]]; then
			pinentry=/opt/homebrew/bin/pinentry
		else
			pinentry=/usr/local/bin/pinentry
		fi
		;;
	*)
		bin=$(gpgconf --list-dirs bindir)

		if [[ -x '/etc/alternatives/pinentry' ]]; then
			pinentry=/etc/alternatives/pinentry
		else
			pinentry=$bin/pinentry
		fi

		case "$PINENTRY_USER_DATA" in
			*USE_TTY*)		pinentry=$bin/pinentry-tty  ;;
			*USE_CURSES*)	pinentry=$bin/pinentry-curses ;;
			*USE_GTK2*)		pinentry=$bin/pinentry-gtk-2 ;;
			*USE_GNOME3*)	pinentry=$bin/pinentry-gnome3 ;;
			*USE_X11*)		pinentry=$bin/pinentry-x11 ;;
			*USE_QT*)		pinentry=$bin/pinentry-qt ;;
		esac
		;;
esac

exec $pinentry "$@"
